apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-ms-alerts-qa
  namespace: cp-qa
  labels:
    environment: qa
spec:
  selector:
    matchLabels:
      app: cp-ms-alerts-qa
  template:
    metadata:
      labels:
        app: cp-ms-alerts-qa
    spec:
      containers:
        image: us.icr.io/bupa-containers/qa/catalogo/cp-ms-alerts-qa:1.1.15
        imagePullPolicy: IfNotPresent
        name: cp-ms-alerts-qa
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: default-us-icr-io
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cp-ms-alerts-qa
                topologyKey: kubernetes.io/hostname
              weight: 100
