apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-web-qa
  namespace: cp-qa
  labels:
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cp-web-qa
  template:
    metadata:
      labels:
        app: cp-web-qa
    spec:
      containers:
        - name: cp-web-qa
          image: registry.birchman.cl/bupa-containers-desarrollo/catalogo-web-container:1.29.25
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cp-web-qa
                topologyKey: 'kubernetes.io/hostname'
